import { createContext, useContext, useState, ReactNode, useCallback } from "react";

type Lang = "ru" | "en";

const dict: Record<Lang, Record<string, string>> = {
  ru: {
    "nav.catalog": "Каталог",
    "nav.cart": "Корзина",
    "nav.account": "Аккаунт",
    "nav.admin": "Админ",
    "hero.title": "СТИЛЬ ДЛЯ СМЕЛЫХ",
    "cart.empty": "Корзина пуста",
    "cart.title": "Корзина",
    "cart.checkout": "Оформить заказ",
    "cart.continue": "Продолжить покупки",
    "cart.total": "Итого",
    "cart.items": "Товары",
    "cart.shipping": "Доставка",
    "cart.free": "Бесплатно",
    "cart.freeThreshold": "До бесплатной доставки осталось",
    "cart.toPay": "К оплате",
    "account.title": "Личный кабинет",
    "account.profile": "Профиль",
    "account.orders": "Заказы",
    "account.wishlist": "Избранное",
    "account.addresses": "Адреса",
    "account.settings": "Настройки",
    "account.logout": "Выйти",
    "account.login": "Вход",
    "account.register": "Регистрация",
    "account.forgot": "Восстановление пароля",
    "account.noAccount": "Нет аккаунта?",
    "account.hasAccount": "Уже есть аккаунт?",
    "account.registerLink": "Зарегистрируйтесь",
    "account.loginLink": "Войдите",
    "account.forgotLink": "Забыли пароль?",
    "account.save": "Сохранить изменения",
    "account.saving": "Сохранение...",
    "account.name": "Имя",
    "account.email": "Email",
    "account.phone": "Телефон",
    "account.password": "Пароль",
    "account.confirmPassword": "Подтвердите пароль",
    "account.changePassword": "Сменить пароль",
    "account.newPassword": "Новый пароль",
    "account.currentPassword": "Текущий пароль",
    "account.myData": "Мои данные",
    "account.myOrders": "Мои заказы",
    "account.noOrders": "У вас пока нет заказов",
    "account.wishlistEmpty": "Список избранного пуст",
    "account.goToCatalog": "Перейти в каталог",
    "account.avatar": "Аватарка",
    "account.address": "Адрес",
    "account.city": "Город",
    "account.street": "Улица, дом",
    "account.apartment": "Квартира",
    "account.zip": "Индекс",
    "product.addToCart": "Добавить в корзину",
    "product.selectSize": "Выберите размер",
    "product.size": "Размер",
    "product.color": "Цвет",
    "product.quantity": "Количество",
    "product.composition": "Состав",
    "product.care": "Уход за изделием",
    "product.delivery": "Доставка и возврат",
    "product.sizeGuide": "Таблица размеров",
    "product.reviews": "Отзывы",
    "product.noReviews": "Пока нет отзывов",
    "product.writeReview": "Написать отзыв",
    "product.freeShipping": "Бесплатная доставка",
    "product.freeShippingDesc": "При заказе от 10 000 ₽",
    "product.return": "Возврат 30 дней",
    "product.returnDesc": "Простой обмен и возврат",
    "product.quality": "Гарантия качества",
    "product.qualityDesc": "Только оригинальные товары",
    "checkout.title": "Оформление заказа",
    "checkout.delivery": "Доставка",
    "checkout.pickup": "Самовывоз",
    "checkout.deliveryAddress": "Адрес доставки",
    "checkout.pickupAddress": "Адрес самовывоза: Москва, ул. Тверская, 1",
    "checkout.contact": "Контактные данные",
    "checkout.firstOrderDiscount": "Скидка на первый заказ -10%",
    "checkout.placeOrder": "Оформить заказ",
    "checkout.ordering": "Оформление...",
    "footer.brand": "Премиальная мужская одежда для тех, кто ценит стиль и качество.",
    "footer.shop": "Магазин",
    "footer.help": "Помощь",
    "footer.contact": "Контакты",
    "footer.rights": "© 2025 PASHE. Все права защищены.",
    "admin.title": "Админ-панель",
    "admin.orders": "Заказы",
    "admin.users": "Пользователи",
    "admin.noAccess": "Нет доступа",
    "common.loading": "Загрузка...",
    "common.back": "Назад",
    "common.submit": "Отправить",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
  },
  en: {
    "nav.catalog": "Catalog",
    "nav.cart": "Cart",
    "nav.account": "Account",
    "nav.admin": "Admin",
    "hero.title": "STYLE FOR THE BOLD",
    "cart.empty": "Cart is empty",
    "cart.title": "Cart",
    "cart.checkout": "Checkout",
    "cart.continue": "Continue shopping",
    "cart.total": "Total",
    "cart.items": "Items",
    "cart.shipping": "Shipping",
    "cart.free": "Free",
    "cart.freeThreshold": "Until free shipping",
    "cart.toPay": "To pay",
    "account.title": "My Account",
    "account.profile": "Profile",
    "account.orders": "Orders",
    "account.wishlist": "Wishlist",
    "account.addresses": "Addresses",
    "account.settings": "Settings",
    "account.logout": "Sign out",
    "account.login": "Sign in",
    "account.register": "Sign up",
    "account.forgot": "Reset password",
    "account.noAccount": "No account?",
    "account.hasAccount": "Already have an account?",
    "account.registerLink": "Sign up",
    "account.loginLink": "Sign in",
    "account.forgotLink": "Forgot password?",
    "account.save": "Save changes",
    "account.saving": "Saving...",
    "account.name": "Name",
    "account.email": "Email",
    "account.phone": "Phone",
    "account.password": "Password",
    "account.confirmPassword": "Confirm password",
    "account.changePassword": "Change password",
    "account.newPassword": "New password",
    "account.currentPassword": "Current password",
    "account.myData": "My data",
    "account.myOrders": "My orders",
    "account.noOrders": "No orders yet",
    "account.wishlistEmpty": "Wishlist is empty",
    "account.goToCatalog": "Go to catalog",
    "account.avatar": "Avatar",
    "account.address": "Address",
    "account.city": "City",
    "account.street": "Street, building",
    "account.apartment": "Apartment",
    "account.zip": "Zip code",
    "product.addToCart": "Add to cart",
    "product.selectSize": "Select size",
    "product.size": "Size",
    "product.color": "Color",
    "product.quantity": "Quantity",
    "product.composition": "Composition",
    "product.care": "Care instructions",
    "product.delivery": "Delivery & returns",
    "product.sizeGuide": "Size guide",
    "product.reviews": "Reviews",
    "product.noReviews": "No reviews yet",
    "product.writeReview": "Write a review",
    "product.freeShipping": "Free shipping",
    "product.freeShippingDesc": "On orders over ₽10,000",
    "product.return": "30-day returns",
    "product.returnDesc": "Easy exchange and return",
    "product.quality": "Quality guarantee",
    "product.qualityDesc": "Only original products",
    "checkout.title": "Checkout",
    "checkout.delivery": "Delivery",
    "checkout.pickup": "Pickup",
    "checkout.deliveryAddress": "Delivery address",
    "checkout.pickupAddress": "Pickup address: Moscow, Tverskaya st., 1",
    "checkout.contact": "Contact details",
    "checkout.firstOrderDiscount": "First order discount -10%",
    "checkout.placeOrder": "Place order",
    "checkout.ordering": "Processing...",
    "footer.brand": "Premium men's fashion for those who value style and quality.",
    "footer.shop": "Shop",
    "footer.help": "Help",
    "footer.contact": "Contact",
    "footer.rights": "© 2025 PASHE. All rights reserved.",
    "admin.title": "Admin Panel",
    "admin.orders": "Orders",
    "admin.users": "Users",
    "admin.noAccess": "Access denied",
    "common.loading": "Loading...",
    "common.back": "Back",
    "common.submit": "Submit",
    "common.delete": "Delete",
    "common.edit": "Edit",
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>(() => {
    return (localStorage.getItem("pashe-lang") as Lang) || "ru";
  });

  const changeLang = useCallback((newLang: Lang) => {
    setLang(newLang);
    localStorage.setItem("pashe-lang", newLang);
  }, []);

  const t = useCallback((key: string) => {
    return dict[lang][key] || dict.ru[key] || key;
  }, [lang]);

  return (
    <LangContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LangContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
